### ISSUE TITLE
Remove "Q-encoding"

### ISSUE THREAD

**Issue by willhite** [attic-labs/noms#1787]
csv-export writes the escaped header names into the exported csv-file. csv-import reads in the escaped names and escapes them again. This causes field names and ultimately the row type to change.

**Comment by mikegray** [comment]
Some general thoughts:

1. Escaping should be idempotent - re-escaping over and over should produce the same result. Currently that is not that case since  Q-escaping will keep re-escaping the Q-codes from previous escaping. Making escaping idempotent would help alleviate the initial problem identified in the first comment above - the row type and column field name changing with export and re-import.

2. Now that we have meta information on commits we could store the original csv headers or the mapping of headers that we needed to encode to the original un-escaped version for use in future exports, maybe.

**Comment by aboodman** [comment]
Agree Mike. I don't know a mechanism to idenpotently escape an unlimited alphabet to a limited one. Do you?

Also I sort of feel that we should be optimizing for legibility here not a collision free / reversible escaping scheme. IOW it would be better if "foo bar" went to "foo_bar" and we handled collisions some other way.

**Comment by willhite** [comment]
I was thinking about this the other day, too. Maybe we shouldn't try so hard on the header thing, just apply a default mapping that works in most cases and allow them to specify column header mappings in the command line. The Q escaping makes for some intolerably ugly field names, IMO.

**Comment by mikegray** [comment]
No I don't know of a mechanism for an unlimited alphabet.  I agree that legibility is the best metric for success here. I agree that `spaces` to `underscores` would be clean. `Spaces` is probably the most common occurrence for headers, with `hyphens` being another likely common and logical mapping to `underscores`. Maybe we should have Zane, while looking for new datasets, keep track of headers/field names so we can get a better sampling of common issues.

**Comment by arv** [comment]
I always envisioned using the meta data for this.

I like @willhite's idea to do a more human friendly encoding and bail if it doesn't work. There is always a manual override switch for the exceptional case.

**Comment by aboodman** [comment]
OK, so new proposal:

1. Replace everything that isn't `[A-Za-Z1-9_]` with `_`.
2. If this produces duplicate column names, error (user must manually map columns in that case)

For now, we won't record the original column names anyplace, but if we ever need full-fidelity re-export, we can do that.

**Comment by aboodman** [comment]
I'm closing this in favor of a clean new bug: #2411
