### ISSUE TITLE
Add support for nested maps to csv-importer and exporter

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#1956]
Summary of resolution: extend the current `-dest-type:map,4` thing to support multiple keys and output a nested map

===

for @kylelundstedt , the monthly loan perf data key'd by loan-id + month.

**Comment by mikegray** [comment]
Do we have some sample data with multiple keys?

**Comment by aboodman** [comment]
I was looking at https://nycopendata.socrata.com/Transportation/Medallion-Vehicles-Authorized/rhe8-mgbb/data. I think that some combination of VIN, License Plate, and License Number may be unique but I never figured it out.

**Comment by aboodman** [comment]
This data changes everyday, so if you can figure out what set of columns is unique that'd be cool to track on demo.noms.io.

**Comment by mikegray** [comment]
That data does not have a set of columns that are unique.

**Comment by aboodman** [comment]
good to know

**Comment by aboodman** [comment]
I guess we'll have to track it with `-dest-type:set` then

**Comment by aboodman** [comment]
Or `-dest-type:multiset` (`Map<T, number>`)

**Comment by aboodman** [comment]
@mikegray: @rafael-atticlabs has a dataset that has a compound key that you can use for development. We cannot redistribute that one though.

**Comment by mikegray** [comment]
where can i get a copy?

**Comment by mikegray** [comment]
@rafael-atticlabs I have this working, but I am concerned with the performance ramifications. We moved to using a StreamingMap/mapMutator/opcache to improve performance for csv-import with dest-type=map, but with the work to fix this issue we have potentially several levels of maps within maps. Since the csv file isn't guaranteed to be sorted (and likely isn't), we need to be able to either ask the StreamingMap/mapMutator/opcache if a key already exists to re-use an already created nested map or we need to basically use non-streaming Maps to be able to re-use already created Maps from earlier processing. Or maybe you have another idea?  Interested in your thoughts.

**Comment by mikegray** [comment]
fixed with #2433
