### ISSUE TITLE
Spin up noms on IPFS (or bittorrent?)

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2123]
I have always thought that it should be pretty straightforward to run noms on top of IPFS. It also seems like it could work on top of Bittorrent.

It would be really fun to see someone take this on.

**Comment by jaseg** [comment]
(on bittorrent)

There are two general ways in which this could work. One could
* Just use the bittorrent DHT to locate peers that have a certain commit, but use the http sync protocol used by other parts of the system to synchronize
 * This has the problem that you can only share immutable commits that way, mutable named references would require some other mechanism to implement. One could e.g. do this by placing a signed commit hash in the DHT at a location identified by the hash of the public key for the signing private key.
 * The bittorrent DHT does have its problems, especially it is not as resilient against malicious attacks as one might want it to be.

* Find some way to deterministically map a noms object (such as a commit) to a torrent. This means:
 * mapping the metadata in some sensible way to torrent metainfo
 * finding a deterministic way to encode the noms object into a blob
   * For this blob-encoding, some intelligent utilization of padding and block size might be useful. Bittorrent is a little ugly in that files and blocks don't need to align. AFAICT it should be possible to encode some noms semantics in the file hierarchy of the torrent.
 * This would mostly be cool because you could just use existing bittorrent infrastructure to share noms datasets.
 * The main issue I see with this is that AFAIK ATM bittorrent does not provide any mechanism that could be used to actually share common objects between two "noms-torrents". This requires some more research.

Personally, I think the latter is more interesting. I don't think noms would gain much from using the bittorrent DHT for some fancy semantics (thing magnet links), and especially looking forward to more widespread IPv6 adoption I would not necessarily want to trust that DHT for the years to come.

OTOH, having a (deterministic!) way to encode noms objects into torrents would IMHO be useful anytime you want to share either large amounts of data or with large amounts of people/computers.

**Comment by flyingzumwalt** [comment]
FYI over the next 12 weeks I'm going to run a series of workshops here in Philadelphia where we walk a group of developers through creating an IPFS adapter for noms. The workshops are going to cover all the foundational topics you need to know about in order to write that adapter (merkle dags, distributed version control, git's data model, noms data model, ipfs, etc.).

We will do our best to make those workshops useful as freestanding reference materials for people to learn at their own pace online.

The Project Page: http://datjawn.com
The announcement: https://codeforphilly.org/projects/dat_tables/updates/9
The Workshops: (work in progress) https://cfabrigadephiladelphia.github.io/decentralized-data/

**Comment by Ericson2314** [comment]
https://codeforphilly.github.io/decentralized-data/ fixed link

**Comment by aboodman** [comment]
@flyingzumwalt what became of this? Do you have an example of the adaptors that were built? I forgot about this bug and started the work again: https://github.com/attic-labs/noms/tree/master/go/ipfs

**Comment by flyingzumwalt** [comment]
We never got around to working on the noms adapter. The run of workshops went well, people learned a lot, but my energies got diverted into data rescue stuff right when we wanted to switch to really coding on stuff.

**Comment by aboodman** [comment]
We did this.
