### ISSUE TITLE
create a 'noms alias' command

### ISSUE THREAD

**Issue by willhite** [attic-labs/noms#2131]
This would be **vastly** superior to a 'noms use' command and easier to implement. The following command:
```noms alias local http://localhost:8000```
would save the alias to a .noms file in the user's home directory. From that point on, users could use the command:
```noms ds local```

The noms alias command would also have the following args: -d (for delete), -s (for show) and -ls (list all).
```
prompt> noms alias -s local
local: http://localhost:8000

prompt> noms alias -ls
local:                http://localhost:8000
cli-tour:             http://demo.noms.io/cli-tour
demo-sfcrime:         http://demo.noms.io/cli-tour::sf-crime

prompt> noms alias -d local
alias 'local' deleted
```

**Comment by kalman** [comment]
> the place we save the configuration should in fact be a noms repo

drive by: I like how .gitconfig is a text file, not git repositories.

**Comment by aboodman** [comment]
>> the place we save the configuration should in fact be a noms repo
> drive by: I like how .gitconfig is a text file, not git repositories.

yeah I had that gut reaction too. I suggested using noms as a kind of strawman.

**Comment by ehalpern** [comment]
Shooting from the hip and taking inspiration from git clone, what if noms defined a mapping between the local and remote repo implicitly when sync was issued. This combined with some prudent defaulting could be a convenient way to work with local and remote datasets.

Here's a rough sketch:

Issuing a sync like this: 
```
noms sync http://demo.noms.io/cli-tour::sf-film-locations ldb:.noms/tour::films
```

would implicitly create some definitions like this: 
```
# .nomsconfig
[db.tour]
  url = ldb:.noms/tour
  [db.tour.remote.origin]
    url = http://demo.noms.io/cli-tour
```    

The `use` command would activate the mappings. (Note that `use` could be implicit if there was only one db defined in the local .nomsconfig). 
```
noms use tour    # activates definitions under db.tour
```

Other noms commands would be modified to make use of the current db mappings: 

```
noms ds          # noms ds ldb://.noms/tour
noms ds origin   # noms ds http://demo.noms.io/cli-tour

noms log films   # noms log ldb://tmp/noms/tour::films
noms log origin::sf-film-locations   # noms log http://demo.noms.io/cli-tour::sf-film-locations

noms show 'it8pop...'         # noms show ldb://.noms/tour::'...'
noms show origin::'it8pop...'  # noms show http://demo.noms.io/cli-tour::'...'

noms sync films origin::sf-film-locations
noms sync origin::sf-film-locations films
``` 

There would also be explicit commands for defining these mappings like:

```
noms config db <name> --set-url <local-url>
noms config db <name> --set-remote <remote-name> <remote-url> 
```   

@aboodman, @willhite: If this feels like a useful idea to pursue, I can flesh out the details and a basic implementation to kick around.

**Comment by willhite** [comment]
I'm not sure about the .ini config file syntax, do they normally scope things with a '.' in the name or is there some other way of scoping.

I think this is pretty cool and it would be nice to leverage the .git model for this onto noms. I can see how the general 'alias' concept might get unwieldy if people have several databases and this might scale better. But I am a bit nervous about how well this concept maps to a system like ours that isn't closely tied to a directory structure like git is. If other people think this is a good direction, I would suggest implementing the bare minimum for us to see how this feels. So perhaps, just implement the config file reader and the integration with dataspec.go. We would each have to create our config files manually for now but it would allow us to get a sense for how well this works.

**Comment by ehalpern** [comment]
The config format in the example is [toml](https://npf.io/2014/08/intro-to-toml/). It's very similar to the git file [format](https://git-scm.com/docs/git-config). Using the git format would require a little more programming but is certainly easy to do if important.

Agreed with the idea of first doing a minimal implementation. This would sanity test the idea and inform how/if to proceed further.

**Comment by ehalpern** [comment]
To be more precise, the minimal implementation would be as follows:

### Step 1: Local and remote aliases

If ./.nomsconfig or ~/.nomsconfig is present, load it.

```
# .nomsconfig
[db.tour]
  url = ldb:.noms/cli-tour
  [db.tour.remote.origin]
    url = http://demo.noms.io/cli-tour
```

The example above defines two db aliases: 
- tour (refers to ldb:.noms/cli-tour) 
- tour.origin (refers to http://demo.noms.io/cli-tour) 

Either of these aliases can be used anywhere in a noms command where a db name is required. Here are some examples:

```
noms ds tour          # noms ds ldb://.noms/cli-tour
noms ds tour.origin   # noms ds http://demo.noms.io/cli-tour

noms log tour::films   # noms log ldb://.noms/cli-tour::films
noms log tour.origin::sf-film-locations   # noms log http://demo.noms.io/cli-tour::sf-film-locations

noms show tour::'it8pop...'         # noms show ldb://.noms/tour::'...'
noms show tour.origin::'it8pop...'  # noms show http://demo.noms.io/cli-tour::'...'
```

### Step 2: Use command

The use command specifies a local database to use as the default. Once issued, this database will be implicit in most noms commands. Additionally remote databases associated with this database will no longer need to be qualified. Here are some examples:

``` 
noms ds          # noms ds ldb://.noms/cli-tour
noms ds origin   # noms ds http://demo.noms.io/cli-tour

noms log films   # noms log ldb://.noms/cli-tour::films
noms log origin::sf-film-locations   # noms log http://demo.noms.io/cli-tour::sf-film-locations

noms show 'it8pop...'          # noms show ldb://.noms/tour::'...'
noms show origin::'it8pop...'  # noms show http://demo.noms.io/cli-tour::'...'
```

**Comment by kalman** [comment]
FWIW I'd rather not have the use functionality.

**Comment by ehalpern** [comment]
@kalman: Can you elaborate on what specifically you don't like about use? 

Is it the idea of a default context (where the local and remote databases may be implicit in commands)? Or is it the idea that there may be multiple contexts?

**Comment by kalman** [comment]
Yeah - here are 5 reasons:

1. The idea of a default git context works for me because it's dependent on shell state, namely the working directory (plus its currently checked out branch). I explicitly enter a state of git by cd'ing into that directory. Noms doesn't have that concept (I suppose you could say "thing of noms pwd as home directory path").
2. A small related point I just thought of: shelling out to commands and leaving out databases (deliberately or accidentally) could be surprising.
3. I can see rules about where the database should be implicitly inserted, and where it shouldn't, could get ambiguous/inconsistent/confusing/frustrating. I can't think of an example right now where the path is ambiguous, but we did have problems resolving ambiguity.
4. Where in the stack does the substitution happen? Does the entire noms library respect the implicit database, or do commands have to opt-in somehow (e.g. what about csv-import)?
5. If I _do_ need to deal with multiple databases, having one be implicit could be surprising. However so long as this whole thing is explicit (you need to noms use it, it never happens implicitly) this should be fine.

**Comment by ehalpern** [comment]
> The idea of a default git context works for me because it's dependent on shell state, namely the working directory (plus its currently checked out branch). I explicitly enter a state of git by cd'ing into that directory. Noms doesn't have that concept (I suppose you could say "thing of noms pwd as home directory path").

My initial thinking was to follow the git model and tie a single context to a directory. This feels clearer and simpler than `noms use` to me also. 

On the negative side, it's a little odd to require cd'ing to an otherwise empty directory. Dan @willhite also raised concern about restricting the user to one local db. My gut is that these negatives may not be too bad in practice.

> A small related point I just thought of: shelling out to commands and leaving out databases (deliberately or accidentally) could be surprising.

Not sure I follow.

> I can see rules about where the database should be implicitly inserted, and where it shouldn't, could get ambiguous/inconsistent/confusing/frustrating. I can't think of an example right now where the path is ambiguous, but we did have problems resolving ambiguity.

I've worried about this a bit and think I can devise simple rules to avoid ambiguity. Won't know for sure until digging into the implementation a bit.

> Where in the stack does the substitution happen? Does the entire noms library respect the implicit database, or do commands have to opt-in somehow (e.g. what about csv-import)?

It would need to apply to all command line tools. Probably makes sense to keep it out of the core API.

> If I do need to deal with multiple databases, having one be implicit could be surprising. However so long as this whole thing is explicit (you need to noms use it, it never happens implicitly) this should be fine.

There might be some confusion here, but my hope is that: 

1. this use case is uncommon (other than pairing a local db with remotes)
2. explicit specs can be handled in an unsurprising way

**Comment by kalman** [comment]
> On the negative side, it's a little odd to require cd'ing to an otherwise empty directory 

I agree. I hadn't really considered this.

> > A small related point I just thought of: shelling out to commands and leaving out databases
> > (deliberately or accidentally) could be surprising.
> Not sure I follow.

As in say I write a script that implements a pipline: e.g. imports data, then transforms it. We actually already have this with the cron jobs where url-fetch imports csv blob, then csv-import turns that into structured data. It also runs various noms commands to make sure not to commit duplicate commits if the blob doesn't change.

I can see easy mistakes slipping in: leaving out arguments by accident and doing the wrong thing, or a bad script running noms use but not restoring it... etc.

**Comment by aboodman** [comment]
I think I'm on board with the directory-based version of this proposal, *except* for I don't like the idea of trying to default the local/remote based on `sync`. I'd rather it be explicit to start out so we can get used to it.

**Comment by aboodman** [comment]
It's a big change so I expect everyone will be a little freaked out, but I think it can be implemented in such a way that it isn't too disruptive to how people work right now and they can try it out.

**Comment by ehalpern** [comment]
Considering the issues raised here and discussing offline with @aboodman, here's a revised proposal:

A noms context is defined when a .noms/config file is present in the current directory or in an ancestor. The config will looks something like this:

```
[local]
url = ldb:.noms/db   # the url of the local database; defaults to ldb:./.noms/db but can be any path    

[remote.origin]     # defines a remote alias named origin 
url = http://demo.noms.io/cli-tour

[remote.another]  #defines a remote alias named another
...
```

When in a directory where the noms context is active, the local database is implied in many commands and remote(s) can be referred to by their aliases: 

```
noms ds             # noms ds ldb:.noms/db 
noms ds origin   # noms ds http://demo.noms.io/cli-tour

noms log ::sf-films                           # noms log ldb://.noms/db::sf-films
noms log origin::sf-film-locations   # noms log http://demo.noms.io/cli-tour::sf-film-locations

noms show ::'it8pop...'                     # noms show ldb://.noms/db::'...'
noms show origin::'it8pop...'           # noms show http://demo.noms.io/cli-tour::'...'

noms diff ::'it8pop...' origin::'it8pop...'    # diff local object with object at origin

noms sync ::sf-films origin::sf-film-locations  # sync from local to remote
noms sync origin::sf-film-locations ::sf-films  # sync from remote to local
``` 

The commands will continue to work with full specs as well. 

When .noms/config isn't present, noms behavior is unchanged. 

There's still a healthy debate about the approach of tying a context to a directory -vs- defining databases and remotes globally. This proposal should be viewed as a prototype to evaluate rather than the final approach.

Implementation steps:

Phase 1:
- Implement config file parsing and discovery
- Resolve aliases in noms commands allowing "local" as an alias for the local database

Phase 2: 
- implement default use of the local db when no db name is specified

**Comment by aboodman** [comment]
On Thu, Sep 8, 2016 at 3:52 PM, Eric Halpern <notifications@github.com>
wrote:

> Considering the issues raised here and discussing offline with @aboodman
> <https://github.com/aboodman>, here's a revised proposal:
>
> A noms context is defined when a .noms/config file is present in the
> current directory or in an ancestor. The config will looks something like
> this:
>
> [local]
> url = ldb:.noms/db   # the url of the local database; defaults to ldb:./.noms/db but can be any path
>
> [remote.origin]     # defines a remote alias named origin
> url = http://demo.noms.io/cli-tour
>
> [remote.another]  #defines a remote alias named another
> ...
>
> When in a directory where the noms context is active, the local database
> is implied in many commands and remote(s) can be referred to by their
> aliases:
>
> noms ds             # noms ds ldb:.noms/db
> noms ds origin   # noms ds http://demo.noms.io/cli-tour
>
> noms log ::sf-films                           # noms log ldb://.noms/db::sf-films
>
>
Can we make it so the '::' not required?

>
> noms log origin::sf-film-locations   # noms log http://demo.noms.io/cli-tour::sf-film-locations
>
> noms show ::'it8pop...'                     # noms show ldb://.noms/db::'...'
> noms show origin::'it8pop...'           # noms show http://demo.noms.io/cli-tour::'...'
>
> noms diff ::'it8pop...' origin::'it8pop...'    # diff local object with object at origin
>
> noms sync ::sf-films origin::sf-film-locations  # sync from local to remote
> noms sync origin::sf-film-locations ::sf-films  # sync from remote to local
>
> The commands will continue to work with full specs as well.
>
> When .noms/config isn't present, noms behavior is unchanged.
>
> There's still a healthy debate about the approach of tying a context to a
> directory -vs- defining databases and remotes globally. This proposal
> should be viewed as a prototype to evaluate rather than the final approach.
>
> Implementation steps:
>
> Phase 1:
>
>    - Implement config file parsing and discovery
>    - Resolve aliases in noms commands allowing "local" as an alias for
>    the local database
>
> Phase 2:
>
>    - implement default use of the local db when no db name is specified
>
>
lgtm

**Comment by kalman** [comment]
> Can we make it so the '::' not required?

You need to be careful because of IPV6 addresses which (as we know) allow `::`. You'd need to know whether the part before `::` is the name of an alias, vs just leaving out the database altogether.

Given IPV6 addresses need to start with `https?://` it should be ok, since we don't allow `:` in dataset names. But good to keep this in mind.

**Comment by ehalpern** [comment]
> Can we make it so the '::' not required?

I think we can as long as we require the protocol prefix in explicit specs.

**Comment by aboodman** [comment]
You should send out a note about this to #general and to the usage mailing
list too...
