### ISSUE TITLE
JS Sequence and friends should not be generic

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#2715]
After hacking on refactoring the JS sequence code (Sequence, SequenceCursor, etc) to be structured the same as Go - which mostly makes sense to me these days - I've concluded that they shouldn't be generic[1]. For once, in the way that Go forces us to use `interface{}` everywhere, it actually makes more sense.

While it first may appear that "a Sequence of Things" where "Thing" is mostly a Value make sense to be generic... it's not always a Value. Sometimes it's a MapEntry, and sometimes it's a MetaTuple.

You can keep chucking generics in there and it mostly works - like the code currently is - but it's a struggle, and for all I know we're just pushing any logic bugs that might be caught by Flow into the types themselves. We're asking a lot of Flow here.

@rafael-atticlabs IIRC you were actually talking about something similar to this last week?

[1] of course, Map, MapEntry, Set, etc should still be generic.

**Comment by kalman** [comment]
More plane hacking occurred:

What ended up falling out was changing the meaning of the `T` variable in the Sequences - instead of being the type of the items in the sequence, it was the type of the *leaf* items in the Sequence. This actually works. I haven't decided if it's actually useful though.

**Comment by rafael-atticlabs** [comment]
Yeah, my idea about this is that both go & js change the semantics around sequence such that it's *always* a `Value` and if what's in the sequence is logically tuples, then the sequence is a known repeating pattern of types.

E.g. `Sequence<MapEntry>`  => `[<foo, 2>, <bar, 3>, <baz, 5>]`

would become 

`Sequence` => `[foo, 2, bar, 3, baz, 5]`

and the low-level sequence logic doesn't have to care about the logical contents of each tuple, but higher level abstractions need to do math to find the right element of each tuple.

I believe this is a necessary first step to lazily decoding sequences (#2270) because that's how the bytes are encoded.

**Comment by rafael-atticlabs** [comment]
nope
