### ISSUE TITLE
When multiple photos are added to a single FB post, only one image is in Attic

### ISSUE THREAD

**Issue by jennabilotta** [attic-labs/noms#2723]
If you create a single facebook post with multiple images attached, Attic will only show one of the photos in your gallery. @aboodman

**Comment by aboodman** [comment]
@kalman 

This happens because the photo indexer falls back to publish date to index by if taken date is not known. Then the deduplication in the UI takes effect and deduplicates a batch of photos that were published together.

I think we still want the photo ordering to be as it is right now, we just want the deduplication to only take into account taken date.

**Comment by aboodman** [comment]
Oh this was fixed a long time ago. Whoopsie.
