### ISSUE TITLE
Un-written p-tree mutations will be ignored by iteration

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2915]
Looking at the read-ahead code, it occurs to me (and it's my fault for missing this in the review), that the read-ahead doesn't check for the presence of "uncommitted" sequences (sequences which are referenced directly from a meta-tuple).

I haven't tried this, but I suspect if you mutate a prolly tree that was read *out of* a `ValueStore` and then iterate over it, the process will probably crash.

cc @ehalpern

**Comment by ehalpern** [comment]
Notes from brief discussion w/ @rafael-atticlabs:

- The bug fix is likely simple. It's just a matter of using the value in metaTuple.child (when set) rather than reading from the store.
- The bigger question is whether lazy sequence writing (which is the purpose of metaTyple.child) is still needed. This optimization of deferred writing sequence chunks until commit. With the advent of GraphBuilder, this optimization may no longer be necessary.
