### ISSUE TITLE
NBS: Remove reverse-order hack in httpBatchStore

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#2982]
In order to allow value writing to send chunks to the server in write-order, I had to take out the code that sorted chunks-to-be-written by ref-height before sending them to the server. Unfortunately, Pull() relies on functionality like this to allow it to process and SchedulePut() chunks in a top-down fashion. There's now a hack that causes httpBatchStore.Flush() to send chunks in reverse-insert-order.

Stop this. Do a good thing instead :-)
@FYI rafael-atticlabs

**Comment by rafael-atticlabs** [comment]
I actually think that this "hack" is a decent half-step towards "the right thing". Sending in reverse order is convenient because it's an in-order scan.

If we could modify sync so that each height level is written in "chunk" order, then just sending chunks in reverse insertion order might actually create *optimal* locality (i.e. not just parent-child, but sibling).

A (later) step three might be to allow "writes" to take place in this order (i.e. top-down, but in correct "chunk" order), so as to avoid the temporary buffering step).

**Comment by rafael-atticlabs** [comment]
Blocked on https://github.com/attic-labs/noms/issues/3178
