### ISSUE TITLE
Auto-configured validation concurrency to be number of CPUs

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3022]

**Comment by rafael-atticlabs** [comment]
e.g. https://github.com/attic-labs/noms/blob/master/go/datas/remote_database_handlers.go#L38

**Comment by cmasone-attic** [comment]
I was thinking about this on the ferry and I'm not sure it's so simple, because the server will be handling multiple requests at the same time. We don't want each writeValue request to try to spin up NumCPU concurrent chunk-decodes, right? We want to have roughly NumCPU decodes going on at the same time, across all requests

**Comment by cmasone-attic** [comment]
nvm, I bought what raf is selling
