### ISSUE TITLE
Implement `ContainCommonSupertype(a, b *types.Type) bool`

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3203]
`ContainCommonSupertype(a, b *types.Type) bool` is defined recursively for `a` & `b`:

* if either type is `Value` => return true
* if they are of different kind => return false
* else
  * if a & b are structs then, return true iff they are the same name and share a field name and the respective types of the field ContainCommonSupertype
  * if a & b are sets or list, return true iff there exists some element type in both where one ContainCommonSupertype the other
  * if a & b are maps, return true iff there exists a common key type and some pair of respective value types ContainCommonSupertype.
  * else, return true.

**Comment by aboodman** [comment]
Nitty question, but do we really want this in Noms? It's not immediately clear to me that it is generally useful to all Noms clients. Same question with `unionTypes()`.

**Comment by ehalpern** [comment]
@rafael-atticlabs, @aboodman:
After digging into the implementation, I'd propose the following refinements to the rules:

**1. Include unions**

If `a` or `b` is a union, return true if any variant of `a` intersects with any variant of `b`

**2. Require that structs have the same name** 

I think this is necessary to enforce the botrunner rule that a type is identified by its name. The new rule becomes:

if a & b are structs then, return true iff they **have the same name** and they share a field name and the respective types of the field intersect

**3. Require that Maps share a key type rather than have key types that intersect**

I don't think it's meaningful to say that two maps intersect unless the key type is the same since any change to a key value can invalidate the relationship between the key the value. Consider two maps:

- a: Map<Struct<x: Number>, Value>  
- b: Map<Struct<x: Number, y:Number>, Value>  

If we marked `a` and `b` as intersecting, what could be meaningfully done with this? We cannot transform `b` into a map that is the shape of `a` since removing the b.key.y would change value of the key and invalidate the mapping. Looking at if from the botrunner perspective, I don't think it would ever make sense to use a map as input if it didn't have at least one key type that was identical to the input key type. Based on that reasoning, I'd propose the following:

if a & b are maps, return true iff **they share a key type and their value types intersect**

**Comment by rafael-atticlabs** [comment]
1) Agree

2) I think we'll require elsewhere that Object must have a non-empty names. Even though it won't be important in some sense it seems more correct to implement it as: both must be named the same OR at least one must be un-named.

3) Agree

**Comment by ehalpern** [comment]
Sounds good.
