### ISSUE TITLE
noms tutorial for nodejs developers

### ISSUE THREAD

**Issue by ansarizafar** [attic-labs/noms#3247]
Is there any tutorial complete available for nodejs developers?
Is it possible to replace MongoDB with noms?
Is data aggregation possible with noms?
Is noms production ready?

**Comment by aboodman** [comment]
On Fri, Mar 3, 2017 at 7:20 AM, Zafar Ansari <notifications@github.com>
wrote:

> Is there any tutorial available for nodejs developers?
>
There is this: https://github.com/attic-labs/noms/blob/master/doc/js-tour.md

But it was removed from the main page because we are significantly
reworking the way that JS interacts with Noms.  Basically, we are going to
remove the Noms/JS implementation and have JS talk to Go via GraphQL.

It would also be possible to embed the Go implementation of Noms as a
native module for Node and build your own bindings, but that would be a
large amount of work.

> Is it possible to replace MongoDB with noms?
>
Theoretically yeah. But...

> Is noms production ready?
>
No.

> Is data aggregation is possible with noms?—
>
That is what Noms does best. Can you provide more detail of what you are
trying to do?

**Comment by ansarizafar** [comment]
I am working on a Nodejs/VueJs/MongoDB project (A subscription based marketplace for office supplies). I am looking for a better option to replace MongoDB, Why?

No support for ACID transactions.
Limited support for relationships between collections.
Aggregation pipeline is insufficient.

> Can you provide more detail of what you are
trying to do?

I am aggregating Subscriptions/Orders /Sales data from different collections for a Dashboard page.

If GraphQL is the primary QL to access a noms db from JavaScript then:

- Will noms provide a client module like Apollo-client? [http://dev.apollodata.com/](http://dev.apollodata.com/)
- Is it possible to write custom GraphQL query/mutations at the back-end (NodeJS)? 
- How authentication/authorization is performed at the DB level for GraphQL requests initiating from from-end.

I don't mind working on bleeding edge. A comprehensive GraphQL tutorial/guide showing how to store, index, query and aggregate data stored in nomsDB will greatly help developers new to noms.

**Comment by kalman** [comment]
We've just removed the noms JS implementation, perhaps file separate issues on graphql?
